[build]
command = "npm run build"
publish = "dist"

[context.production.environment]
NODE_VERSION = "10.15.3"
NODE_ENV = "production"

[dev]
command = "npm run start"
framework = "#custom"
publish = "dist"
port = 3_000
targetPort = 8_181
NODE_ENV = "development"

[[redirects]]
from = "/post/*"
to = "/blog/:splat"
